#!/bin/bash
nano /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >> /etc/locale.conf
echo muriz > /etc/hostname
nano /etc/hosts
pacman -S grub networkmanager network-manager-applet
grub-install -target=i386-pc /dev/sda
grub-mkconfig -o /boot/grub/grub.cfg
grub-install /dev/sda
grub-mkconfig -o /boot/grub/grub.cfg
systemctl enable NetworkManager
passwd
useradd -m -g users -G wheel -s /bin/bash muriz
EDITOR=nano visudo
passwd muriz
exit
reboot 
