#!/bin/bash
echo "en_US.UTF-8" > /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >> /etc/locale.conf
echo muriz > /etc/hostname
echo "127.0.0.1 localhost" >> /etc/hosts
echo "::1       localhost" >> /etc/hosts
echo "127.0.1.1 arch.localdomain muriz" >> /etc/hosts
pacman -S grub networkmanager network-manager-applet
grub-install /dev/sda
grub-mkconfig -o /boot/grub/grub.cfg
systemctl enable NetworkManager
passwd
useradd -m -g users -G wheel -s /bin/bash muriz
EDITOR=nano visudo
passwd muriz 
